services:
  cli:
    build:
      context: .
      target: cli
      dockerfile: Dockerfile
    image: "laravel-mysql-dump-php-local"
    env_file: .env
    volumes:
      - ./:/opt/apps/app
    depends_on:
      laravel-mysql-dump-mysql:
        condition: service_healthy
    networks:
      - laravel-mysql-dump

  laravel-mysql-dump-mysql:
    container_name: laravel-mysql-dump-mysql
    image: mysql/mysql-server:8.0
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - laravel-mysql-dump-mysql:/var/lib/mysql
      - ./docker/mysql/grant-tenants-db-access.sh:/docker-entrypoint-initdb.d/10-grant-tenants-db-access.sh
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
      retries: 3
      timeout: 5s
    networks:
      - laravel-mysql-dump

volumes:
  laravel-mysql-dump-mysql:

networks:
  laravel-mysql-dump:
    driver: bridge
